### PR TITLE
updated Readme file

### PR DESCRIPTION
**Pull request by kingami34**
Please preview Readme file

### CODE REVIEW

**Comment by kingami34** [comment]
Readme file pull request.

**Review by WilliamCrownover — APPROVED** [review]
I think this is a fine start. We can fill out details closer to completion.

I am a little confused that there is a MIT license badge at the top of the README but an Apache license in the license section on the bottom. We should choose one.

**Review by Hotsoup22 — APPROVED** [review]
looks great! but #credits section is missing.

**Comment by kingami34** [comment]
That needs to be updated

**Review by WilliamCrownover — APPROVED** [review]
Thanks for fixing that!

**Review by kingami34 — COMMENTED** [review]
Looks good.

**Pull request merged**
